.travis.yml
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
=> #5 - added travis build file

com.github.camel-tooling.lsp.eclipse.client/pom.xml
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
=> fixed problem that lsp server was not found in remote repos

camel-lsp-target-platform/pom.xml, com.github.camel-tooling.lsp.eclipse.client.tests.integration/pom.xml, com.github.camel-tooling.lsp.eclipse.client/pom.xml, com.github.camel-tooling.lsp.eclipse.updatesite/pom.xml, pom.xml
=> #14 - Update Maven Module name after split of repositories

com.github.camel-tooling.lsp.eclipse.client/plugin.xml
=> Fix package names used in extension points

com.github.camel-tooling.lsp.eclipse.updatesite/category.xml, com.github.cameltooling.lsp.eclipse.client.feature/.project, com.github.cameltooling.lsp.eclipse.client.feature/build.properties, com.github.cameltooling.lsp.eclipse.client.feature/feature.xml, com.github.cameltooling.lsp.eclipse.client.feature/pom.xml, pom.xml
=> #20 - provide feature and category for update site

README.md
=> #20 - update readme to have installation based on Marketplace

.travis.yml, pom.xml
=> #25 - Activate Sonar analysis

README.md
=> #33 - improve readme for provided features

.travis.yml, website/index.html
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
=> #21 - provide a index.html in the repo folders

camel-lsp-target-platform/camel-lsp-target-platform.target, com.github.camel-tooling.lsp.eclipse.client/META-INF/MANIFEST.MF
- debug adapter protocol ready
- fixing several little issues
=> #30 - upgrade to Photon version

pom.xml
=> Specify runtime environment #50

com.github.camel-tooling.lsp.eclipse.client/pom.xml
and upgrade to latest server version
=> Decorrelate server version from eclipse plugin #63

com.github.camel-tooling.lsp.eclipse.client.tests.ui/plugins/com.github.cameltooling.lsp.reddeer/src/com/github/cameltooling/lsp/reddeer/editor/SourceEditor.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/CamelLSPCompletionTest.java
Signed-off-by: Dominik Jelinek <djelinek@redhat.com>
=> Improve stability of UI test - CamelLSPCompletionTest #65

com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/pom.xml
Signed-off-by: Tomáš Sedmík <tsedmik@redhat.com>
=> Fix UI tests for macOS

com.github.camel-tooling.lsp.eclipse.client.tests.integration/src/main/java/com/github/cameltooling/eclipse/client/tests/integration/CamelLSPStreamConnectionProviderIT.java
=> Cannot rely anymore on inputstream to know if the server has started #76

pom.xml
=> Upgrade Tycho #79

.travis.yml
=> Fix build (oraclejdk8 and xvfb)

com.github.camel-tooling.lsp.eclipse.client/plugin.xml
camel-tooling/camel-language-server#163
requires https://github.com/camel-tooling/camel-language-server/pull/248
=> Support completion for Camel-K Groovy

com.github.camel-tooling.lsp.eclipse.client/plugin.xml
camel-tooling/camel-language-server#254
limitation: it doesn't work inside Java Properties editor
requires https://github.com/camel-tooling/camel-language-server/pull/256
=> Provide Camel Kafka Connect support with generic editor

com.github.camel-tooling.lsp.eclipse.client/plugin.xml
=> Support Camel-K Kotlin files camel-tooling/camel-language-server#255

com.github.camel-tooling.lsp.eclipse.client/plugin.xml
integration done only in generic text editor
requires https://github.com/camel-tooling/camel-language-server/pull/262
=> Support Camel-K JS files camel-tooling/camel-language-server#261

.travis.yml
=> Exclude dependabot branches from non-PR jobs #95

com.github.camel-tooling.lsp.eclipse.client/plugin.xml
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
=> added CamelK YAML support #284

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: Dominik Jelinek <djelinek@redhat.com>
=> Provide GitHub templates for new issues and PRs #67

README.md, com.github.camel-tooling.lsp.eclipse.client.tests.integration/src/main/java/com/github/cameltooling/eclipse/client/tests/integration/CamelCatalogVersionIT.java, com.github.camel-tooling.lsp.eclipse.client.tests.integration/src/main/java/com/github/cameltooling/eclipse/client/tests/integration/CamelLSPLoadedByExtensionPointIT.java, com.github.camel-tooling.lsp.eclipse.client.tests.integration/src/main/java/com/github/cameltooling/eclipse/client/tests/integration/TestSetupHelper.java, com.github.camel-tooling.lsp.eclipse.client/META-INF/MANIFEST.MF, com.github.camel-tooling.lsp.eclipse.client/plugin.xml, com.github.camel-tooling.lsp.eclipse.client/src/com/github/cameltooling/eclipse/client/CamelLSPStreamConnectionProvider.java, com.github.camel-tooling.lsp.eclipse.client/src/com/github/cameltooling/eclipse/internal/l10n/Messages.java, com.github.camel-tooling.lsp.eclipse.client/src/com/github/cameltooling/eclipse/internal/l10n/messages.properties, com.github.camel-tooling.lsp.eclipse.client/src/com/github/cameltooling/eclipse/preferences/CamelLanguageServerPreferenceManager.java, com.github.camel-tooling.lsp.eclipse.client/src/com/github/cameltooling/eclipse/preferences/CamelLanguageServerPreferencePage.java
version
1. Green build for master branch
4. Approved PR
4. [ ] Green **master** branch build
=> FUSETOOLS2-57 - provide preference to use a specific Camel Catalog

com.github.camel-tooling.lsp.eclipse.client/META-INF/MANIFEST.MF, com.github.camel-tooling.lsp.eclipse.client/src/com/github/cameltooling/eclipse/internal/l10n/Messages.java, com.github.camel-tooling.lsp.eclipse.client/src/com/github/cameltooling/eclipse/internal/l10n/messages.properties, com.github.camel-tooling.lsp.eclipse.client/src/com/github/cameltooling/eclipse/preferences/CamelLanguageServerPreferenceManager.java, com.github.camel-tooling.lsp.eclipse.client/src/com/github/cameltooling/eclipse/preferences/CamelLanguageServerPreferencePage.java, com.github.camel-tooling.lsp.eclipse.client/src/com/github/cameltooling/eclipse/preferences/MultilineStringFieldEditor.java
- needs to be provided as a List of components respecting the JSON Camel
Catalog syntax
- no validation in UI, if invalid, just ignored it with a trace in log.
requires https://github.com/camel-tooling/camel-language-server/pull/331
1. Green build for master branch
4. Approved PR
4. [ ] Green **master** branch build
=> FUSETOOLS2-71 - Preference to add additional components

com.github.camel-tooling.lsp.eclipse.client/pom.xml
1. Green build for master branch
4. Approved PR
4. [ ] Green **master** branch build
=> FUSETOOLS2-561 - upgrade Camel Language server to 1.2.0-SNAPSHOT

.travis.yml
1. Green build for master branch
4. Approved PR
4. [ ] Green **master** branch build
=> FUSETOOLS2-596 - use Java 11 for Sonar Analysis

.circleci/config.yml
- build
- test
- sonar analysis
- prepare update site to upload
remains for another iteration: actual publishing of the update site
=> FUSETOOLS2-880 - Add first iteration of Circle CI

com.github.camel-tooling.lsp.eclipse.client/plugin.xml
=> FUSETOOLS2-962 - fix language server naming

com.github.camel-tooling.lsp.eclipse.client.tests.integration/src/main/java/com/github/cameltooling/eclipse/client/tests/integration/AbtractPreferencesIT.java, com.github.camel-tooling.lsp.eclipse.client.tests.integration/src/main/java/com/github/cameltooling/eclipse/client/tests/integration/CamelRuntimeProviderIT.java, com.github.camel-tooling.lsp.eclipse.client/META-INF/MANIFEST.MF, com.github.camel-tooling.lsp.eclipse.client/src/com/github/cameltooling/eclipse/internal/l10n/Messages.java, com.github.camel-tooling.lsp.eclipse.client/src/com/github/cameltooling/eclipse/internal/l10n/messages.properties, com.github.camel-tooling.lsp.eclipse.client/src/com/github/cameltooling/eclipse/preferences/CamelLanguageServerPreferenceManager.java, com.github.camel-tooling.lsp.eclipse.client/src/com/github/cameltooling/eclipse/preferences/CamelLanguageServerPreferencePage.java, com.github.camel-tooling.lsp.eclipse.client/src/com/github/cameltooling/eclipse/preferences/runtimeprovider/CamelRuntimeProvider.java
requires https://github.com/camel-tooling/camel-language-server/pull/556
=> FUSETOOLS2-963 - provide settings for runtime provider

camel-lsp-target-platform/camel-lsp-target-platform.target, com.github.camel-tooling.lsp.eclipse.client.tests.integration/META-INF/MANIFEST.MF, com.github.camel-tooling.lsp.eclipse.client.tests.ui/plugins/com.github.cameltooling.lsp.reddeer/.classpath, com.github.camel-tooling.lsp.eclipse.client.tests.ui/plugins/com.github.cameltooling.lsp.reddeer/.settings/org.eclipse.jdt.core.prefs, com.github.camel-tooling.lsp.eclipse.client.tests.ui/plugins/com.github.cameltooling.lsp.reddeer/META-INF/MANIFEST.MF, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/.classpath, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/.settings/org.eclipse.jdt.core.prefs, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/META-INF/MANIFEST.MF, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/launcher/RedDeer Test.launch, com.github.camel-tooling.lsp.eclipse.client/META-INF/MANIFEST.MF
some java SE 11 minimal execution environment are required
=> FUSETOOLS2-568 - upgrade target platform to Eclipse 2021-03

pom.xml
requires https://github.com/camel-tooling/camel-lsp-client-eclipse/pull/128
=> Upgrade compiler level to java11

.circleci/config.yml
=> FUSETOOLS2-1234 - FUSETOOLS2-1049 - provide screenshots of Ui tests in

camel-lsp-target-platform/camel-lsp-target-platform.target, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/META-INF/MANIFEST.MF
=> FUSETOOLS2-1622: [eclipse-lsp] Update target platform dependencies

com.github.camel-tooling.lsp.eclipse.client.tests.ui/plugins/com.github.cameltooling.lsp.reddeer/src/com/github/cameltooling/lsp/reddeer/utils/AboutEclipsePage.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/PluginInstalledTest.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/suite/SmokeTests.java
=> FUSETOOLS2-157: [eclipse-lsp] Create UI Tests for installed plugin info

com.github.camel-tooling.lsp.eclipse.client.tests.ui/plugins/com.github.cameltooling.lsp.reddeer/src/com/github/cameltooling/lsp/reddeer/utils/AboutEclipsePage.java
Signed-off-by: Dominik Jelinek <djelinek@redhat.com>
4. Approved PR
=> FUSETOOLS2-1651: [eclipse-lsp] PluginInstalled UI test is unstable on Windows

com.github.camel-tooling.lsp.eclipse.client.tests.ui/plugins/com.github.cameltooling.lsp.reddeer/src/com/github/cameltooling/lsp/reddeer/utils/CreateNewEmptyFile.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/plugins/com.github.cameltooling.lsp.reddeer/src/com/github/cameltooling/lsp/reddeer/wizard/NewJavaClassFirstPage.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/plugins/com.github.cameltooling.lsp.reddeer/src/com/github/cameltooling/lsp/reddeer/wizard/NewJavaClassWizard.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/resources/java-editor-completion-test-route.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/JavaEditorCompletionTest.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/suite/SmokeTests.java
=> FUSETOOLS2-160: Add UI Tests for auto-completion inside Java Editor

README.md
=> FUSETOOLS2-1847: Add new supported features into README

com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/JavaEditorCompletionTest.java
JavaEditorCompletionTest.testComponentSchemes
it will help to investigate flakiness of the test
=> Provide more information in case of test failure

com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/suite/SmokeTests.java
=> FUSETOOLS2-1864: Add CamelRuntimeProviderFeatureTest to SmokeTests

.github/workflows/maven.yml, com.github.camel-tooling.lsp.eclipse.client.tests.ui/plugins/com.github.cameltooling.lsp.reddeer/src/com/github/cameltooling/lsp/reddeer/editor/EditorComponentControl.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/plugins/com.github.cameltooling.lsp.reddeer/src/com/github/cameltooling/lsp/reddeer/editor/SourceEditor.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/plugins/com.github.cameltooling.lsp.reddeer/src/com/github/cameltooling/lsp/reddeer/utils/AboutEclipsePage.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/AdditionalComponentFeatureTest.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/CamelCatalogVersionFeatureTest.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/CamelRuntimeProviderFeatureTest.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/DefaultLSPCompletionTest.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/DefaultTest.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/JavaEditorCompletionTest.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/KafkaDynamicCompletionTest.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/PluginInstalledTest.java, com.github.camel-tooling.lsp.eclipse.client.tests.ui/tests/com.github.cameltooling.lsp.ui.tests/src/com/github/cameltooling/lsp/ui/tests/utils/TimeoutPeriodManipulator.java
=> FUSETOOLS2-1859: Refactor whole suite

com.github.camel-tooling.lsp.eclipse.client/pom.xml
requires https://github.com/camel-tooling/camel-language-server/pull/938
=> Upgrade Camel Language Server to 1.11.0-SNAPSHOT

pom.xml
follow-up https://github.com/camel-tooling/camel-lsp-client-eclipse/pull/209
=> FUSETOOLS2-1905 - specify organization for Sonar
